FORMAT: 1A
HOST: http://polls.apiblueprint.org/
# Quizzy 
    An Api for taking quizzes


# User
## Users Collection [/users]
### Create a User [POST]
+ Request (application/json)

    + Body 
        {
            "username": "me",
            "password": "me"
        }

+ Response 200 (application/json)

    + Body
    {
        "id": 1,
        "username" : "me"
    }

### Update User[PUT]

+ Request (application/json)

    + Body
    {
        "username" : "me",
        "password" : "me",
        "newpassword" : "not-me"
    }
    
+ Response 200 (application/json)

    + Body
    {
        "id": 1,
        "username": "me"
    }